name: OCaml CI

on:
  - push 
  - pull_request

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - run: opam install . --deps-only --with-test
        working-directory: ./etl

      - run: opam exec -- dune build
        working-directory: ./etl

      - run: opam exec -- dune runtest
        working-directory: ./etl

  lint-fmt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./etl

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - name: Install OCamlFormat
        run: opam install ocamlformat
    
      - name: Run OCamlFormat Linter
        run: opam exec -- dune fmt --check
        working-directory: ./etl
